messages:
  noarg: "You need to enter at least one argument!"
  bad_instance: "You cant use this command in console"
  badarg: "This argument does not exist"
  alreadyexist: "You already have eshop"
  eshopcreated: "You have succesfully created your eshop"
  cantload: "This gui cant be load."